name: LINT
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - run: npm run format
      - run: npm run lint
      - run: npm run stylelint
